# Generated by Django 5.2.7 on 2025-10-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_id", models.CharField(max_length=40, unique=True)),
                ("origin", models.CharField(max_length=120)),
                ("destination", models.CharField(max_length=120)),
                ("eta", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_transit", "In Transit"),
                            ("delayed", "Delayed"),
                            ("delivered", "Delivered"),
                        ],
                        default="in_transit",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
