# Generated by Django 5.2.7 on 2025-10-29 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipment",
            options={"ordering": ["eta", "tracking_id"]},
        ),
        migrations.AddField(
            model_name="shipment",
            name="carrier",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="shipment",
            name="contents",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shipment",
            name="departure_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="driver_contact",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="shipment",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="medium",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_transit", "In Transit"),
                    ("delayed", "Delayed"),
                    ("on_time", "On Time"),
                    ("issue", "Issue"),
                    ("delivered", "Delivered"),
                ],
                default="in_transit",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("description", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional material icon name used to visually differentiate events.",
                        max_length=32,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
